### ISSUE TITLE
ERROR of esteps in 1.10.0

### ISSUE THREAD

**Issue by kaji331** [cancerit/CaVEMan#56]
I use python3 to make many esteps running at the same time. Some errors showed to me. I still can get the vcf files. See the attachment. Ubuntu 16.04 x86-64
![2016-11-15 17-52-51](https://cloud.githubusercontent.com/assets/6041206/20330258/745b88c2-abd8-11e6-85cb-e04d3584914c.png)

**Comment by kaji331** [comment]
bad internet!!! Please email me, I will send the attachment information
kaji331@hotmail.com

**Comment by drjsanger** [comment]
Hi @kaji331 ,

This was due to incorrect checking of the returned status of the fclose in estep.c. 
Please try [CaVEMan version 1.10.1](https://github.com/cancerit/CaVEMan/releases/tag/1.10.1). Since this is the only change in 1.10.1 you can prevent having to run the whole of CaVEMan again by manually editing the version string in the caveman.cfg.ini file.
