### ISSUE TITLE
Output for every site?

### ISSUE THREAD

**Issue by matthew-ackerman** [cancerit/CaVEMan#90]
By default, caveman produces a file with a list of variants it has found in each sample. If a site does not contain a variant, caveman produces no output for that site. Sites may have no detected variant for a number of reasons, for instance, there may have been very low coverage at the site, or the site may have been masked, or some sort of filter may have been applied.  My use case requires me to know why caveman has decided not to call a variant at a site. Is there any way to obtain this information?

**Comment by drjsanger** [comment]
Hi @matthew-ackerman . 

The output file `.no_analysis.bed`  will tell you if the position was not analysed at all (due to zero 'CaVEMan visible' coverage, zero copy number in normal or nomparator, or presence in the ignore regions file). 

In order to see output for every single position analysed by CaVEMan you can use the debug option in the estep `caveman estep ... --debug` . This will give an extra file with an entry for EVERY analysed position so will take up a lot of space.

**Comment by matthew-ackerman** [comment]
Thanks!
